In [29]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [30]:
#importnig train data
filename = ('forestfires.csv')
df = pd.read_csv(filename)

In [31]:
##Dropping the month and day columns as we already have the dummy values for day and month in following columns
df.drop(["month","day"],axis=1,inplace =True)
df.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1,...,0,0,0,0,1,0,0,0,0,small
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1,...,0,0,0,0,1,0,0,0,0,small
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,0,...,0,0,0,0,1,0,0,0,0,small

In [32]:
#splitting data into x and y

x = df.iloc[:,1:-1]
y = df.iloc[:,-1]

In [33]:
#Normalizing data

def norm_func(i):
    X = (i-i.min())/(i.max()-i.min())
    return (X)
x = norm_func(x)

In [34]:
# dividing data into train and test 
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20)

In [35]:
x_train.head()

,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,daymon,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
322,0.406272,0.909581,0.133690,0.469453,0.152941,0.400000,0.0,0.000926,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
229,0.278084,0.554591,0.212121,0.456592,0.329412,0.400000,0.0,0.065362,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.442453,0.802979,0.124777,0.350482,0.564706,0.555556,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
118,0.133012,0.092295,0.110517,0.270096,0.176471,0.400000,0.0,0.000000,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
178,0.281875,0.853524,0.110517,0.517685,0.352941,0.200000,0.0,0.004474,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## Grid Search CV

#### fitting gridsearch model to find out optimum values for SVM

In [36]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,0.5],'C':[10,1,0.001]}]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [10, 1, 0.001], 'gamma': [50, 5, 0.5],
                          'kernel': ['rbf']}])

In [37]:
gsv.best_params_ , gsv.best_score_

({'C': 0.001, 'gamma': 50, 'kernel': 'rbf'}, 0.7264808362369337)

### Fitting the SVM model now with grid search results for best model

In [38]:
clf = SVC(C = 0.001, gamma = 50,kernel = 'rbf')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test,y_pred)*100
print("Accuracy = ", acc)
confusion_matrix(y_test,y_pred)

Accuracy =  75.0

array([[ 0, 26],
       [ 0, 78]])